### ISSUE TITLE
Is LLVMCreatePassManager the intended function for FuncPassManager to use?

### ISSUE THREAD

**Issue by MinusGix** [zshipko/llama#7]
When using `FuncPassManager` to add some transforms, merely creating it and telling it to run (without even adding transforms) is enough to cause a crash due to `corrupted_size vs prev_size` (something to do with writing memory outside of where you should).  
I believe this is due to the code in `FuncPassManager::new` calling `LLVMCreatePassManager` rather than `LLVMCreateFunctionPassManager` (which is deprecated, but has a replacement of `LLVMCreateFunctionPassManagerForModule`). The code uses `LLVMRunFunctionPassManager`, which is part of what made me wonder if it was getting the wrong type.  
  
Replacing the `LLVMCreatePassManager` call with `LLVMCreateFunctionPassManagerForModule`, and adding the needed `&Module<'a>` parameter, made so expected usage of the code (adding transforms and running them) worked.  
Also, I wonder if perhaps `run` should be made unsafe since it takes in a `Transform` which is an arbitrary unsafe function that it then calls.

**Comment by zshipko** [comment]
Thanks! I just pushed a commit to use `LLVMCreateFunctionPassManagerForModule` and marked `run` as unsafe.

**Comment by MinusGix** [comment]
Thanks for fixing it!

**Comment by MinusGix** [comment]
Actually, `run` is probably fine, I'm not sure why I said `run`, so I'll blame writing out the issue before I slept.  
The function I was thinking of when I wrote the idea of having it marked as unsafe is `add`, since it takes (essentially) a slice of `Transform` functions which are arbitrary unsafe functions and it runs them on the pass manager instance. `run` is probably fine since it only operates on its own created pass manager, and a given reference to a module.

**Comment by zshipko** [comment]
Ah yeah, I wasn't really thinking about it this morning either. I just published a new release too... I will move the `unsafe` to add and make another release right now.
