### ISSUE TITLE
Show generated IR on verification failure

### ISSUE THREAD

**Issue by dccsillag** [zshipko/llama#8]
IR verification in `function_body`, as is currently done, is more bothersome than helpful.

I'm currently in the following struggle: my code generates invalid IR, and the `verify` call correctly tells me so. However, now I have to solve the issue, without being able to look at the generated IR -- which is proving to be extremely tough, since LLVM failed verification messages leave a lot to be desired.

It would be great if there was some way in which I could display the generated IR in the case of verification failure -- or, some way to run some closure that will access&print the generated IR before the verification happens. Or, simply remove the verification from `function_body`, and have it be run on the whole module at the end of code generation (on request of the user?).

**Comment by zshipko** [comment]
I think it sounds like a good idea to remove the call to `verify` and let users determine when that check should be done. I just made that change here: https://github.com/zshipko/llama/commit/5d9dfdc085d804404870ff6eb80b2998521124ce

**Comment by zshipko** [comment]
I've also just made a new minor release (0.11.1) with this update

**Comment by dccsillag** [comment]
Thank you! Looks like a good change, and everything seems in order.

Already helped me solve my issue :smile:
