### ISSUE TITLE
Is Module::verify correct?

### ISSUE THREAD

**Issue by dccsillag** [zshipko/llama#9]
I've taken the example at https://github.com/zshipko/llama/tree/master/examples and added a call to Module::verify, as well as a print to show the generated IR:

```diff
diff --git a/src/main.rs b/src/main.rs
index a9fa3bf..7e42353 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -17,18 +17,21 @@ impl<'ctx> CodeGen<'ctx> {
     fn jit_compile_sum(&mut self) -> Result<SumFunc, Error> {
         let i64 = Type::i64(&self.context)?;
         let sum_t = FuncType::new(i64, [i64, i64, i64])?;
-        self.engine
-            .module()
-            .declare_function(&self.build, "sum", sum_t, |f| {
-                let params = f.params();
-                let x = params[0];
-                let y = params[1];
-                let z = params[2];
-
-                let sum = self.build.add(x, y, "sum")?;
-                let sum = self.build.add(sum, z, "sum")?;
-                self.build.ret(sum)
-            })?;
+        let module = self.engine.module();
+
+        module.declare_function(&self.build, "sum", sum_t, |f| {
+            let params = f.params();
+            let x = params[0];
+            let y = params[1];
+            let z = params[2];
+
+            let sum = self.build.add(x, y, "sum")?;
+            let sum = self.build.add(sum, z, "sum")?;
+            self.build.ret(sum)
+        })?;
+
+        println!("{module}");
+        module.verify().expect("module verification failed");

         unsafe { self.engine.function("sum") }
     }
```

This generates the following IR, which I'm pretty sure is correct:

```llvm
; ModuleID = 'sum'
source_filename = "sum"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

define i64 @sum(i64 %0, i64 %1, i64 %2) {
entry:
  %sum = add i64 %0, %1
  %sum1 = add i64 %sum, %2
  ret i64 %sum1
}
```

Yet, the `module.verify()` fails, with an empty message:

```
thread 'main' panicked at 'module verification failed: Message()', src/main.rs:34:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

(This also happens in my own code.)

If we compare the two `verify` functions in `llama`, it looks to me like `Module::verify` is checking for `==1` when it should be checking for `==0`: https://github.com/zshipko/llama/blob/85783059ca494c258fc28f9f56ded678642ce726/src/module.rs#L140-L158, https://github.com/zshipko/llama/blob/2b85ef4a0858d678b1871e0a201fa2922ac9fce3/src/value.rs#L261-L275

I couldn't find proper documentation on LLVM about the return code of these functions though, so I'm not too sure. Wdyt?

**Comment by zshipko** [comment]
I think you're right - although it may have switched at some point because I remember some inconsistencies between the function verification and module verification - I will push a fix for this right now.

**Comment by dccsillag** [comment]
Thanks!

**Comment by zshipko** [comment]
Just made a 0.11.2 release with this change
